### ISSUE TITLE
`undefined is not an object (evaluating 'p.ctor')`

### ISSUE THREAD

**Issue by zeckalpha** [Dandandan/parser#15]
Hello!

This is a handy library! I made a lisp, and am refactoring a s-expression library out of it, however, I seem to be running into issues with `Parser.recursively`. It compiles fine, but then I get the JavaScript error: `undefined is not an object (evaluating 'p.ctor')`.

Here's what I have for now.

~~~ haskell
module Sexp where

import String
import List
import Graphics.Element

import Parser
import Parser exposing (Parser, (<*>), (<$>))
import Parser.Char

type Sexp
  = SexpList (List Sexp)
  | SexpElement String

parse string =
  Parser.parse parser' string

parser' =
  Parser.recursively (\() -> parser)

parser =
  Parser.or listParser elementParser

listParser =
  SexpList <$>
    (Parser.Char.parenthesized
      <| Parser.separatedBy parser' whitespaceParser)

elementParser =
  SexpElement << String.fromList <$>
    (Parser.some
      <| Parser.satisfy
        <| \c -> not ((isWhitespace c) || c == '(' || c == ')'))

whitespaceParser =
  Parser.satisfy isWhitespace

isWhitespace char =
  List.member char <| String.toList " \t\r\n\v\f"

main : Graphics.Element.Element
main = Graphics.Element.show
  <| parse "((test) test)"
~~~

I've tried a few different combinations of wrapping the sub-parsers with recursively, and different combinations of the recursively call / not recursively everywhere. I can't seem to figure it out.

**Comment by zeckalpha** [comment]
I don't know why, but for some reason when I inline nearly everything, this works:

~~~ haskell
module Sexp where

import String
import List
import Graphics.Element

import Parser
import Parser exposing (Parser, (<*>), (<$>))
import Parser.Char

type Sexp
  = SexpList (List Sexp)
  | SexpElement String

parser' =
  Parser.recursively (\() ->
    Parser.or
      (SexpList <$>
        (Parser.Char.parenthesized
          <| Parser.separatedBy parser' (Parser.satisfy <| \c -> (List.member c <| String.toList " \t\r\n\v\f"))))
      (SexpElement << String.fromList <$>
        (Parser.some
          <| Parser.satisfy
            <| \c -> not (List.member c <| String.toList " \t\r\n\v\f()"))))

main : Graphics.Element.Element
main = Graphics.Element.show
  <| Parser.parse parser' "((test) test)"
~~~

**Comment by Dandandan** [comment]
Cool!
This is probably a bug in the Elm compiler.

**Comment by zeckalpha** [comment]
That's what I was thinking, but I wasn't sure. Should I open a bug over there?

**Comment by zeckalpha** [comment]
I published this: https://github.com/zeckalpha/elm-sexp

Closing for now. I'd like to refactor it into sub-parsers, but I can't figure out what's going on.

**Comment by Dandandan** [comment]
Nice:), cool parser! I think you should open a bug there, you could probably help by checking if it's also a bug in the upstream compiler.

**Comment by jdavidberger** [comment]
Running into this issue too. I tracked it down a little bit -- the compiler is outputting all the var's in js land in an invalid order; so that when one parser is being initialized that has a reliance on another it is just plain uninitialized. I imagine the inlining either stabalizes the order or forces it. 

If you make every top-level declaration involved in a cycle enveloped in 'Parser.recursively (\() -> ... )' it looks like it should always work. I'm going to check into how elm handles these cycles for other types. 

If there isn't a performance hit for lazy Parser types I'd almost just say make everything lazy, but I imagine there is a large runtime penalty for that.

**Comment by zeckalpha** [comment]
Maybe there could be a submodule Parser.Lazy that makes that assumption?

As for fixing the compiler, would having it put variable declarations (not definitions) at the top of a module scope account for this?

**Comment by jdavidberger** [comment]
Here is a minimal example not using anything in parser -- http://share-elm.com/sprout/55afbea7e4b06aacf0e8b5f2. Also see the new issue that references this one. 

If I understand you right, and by variable declarations you mean the type annotations, I don't think those matter. Ordering of the definitions (a = ...) does seem to matter, just in the exact opposite way I thought it would -- seems like top definitions are done last in the JS, but this is probably arbitrary behavior and not reliable. 

Having looked briefly at the JS generated, I'm a little unclear on if there is an easy fix. I did a brief issues search against elm-compiler and didn't find anything, so I'm went ahead and filed an issue. Not sure what evan is going to do with this though.

**Comment by zeckalpha** [comment]
No, I meant in the js output, not the type annotations in the Elm source.

**Comment by zeckalpha** [comment]
Instead of:
```javascript
   var b = A2(Node,
   "b",
   _L.fromArray([a]));
   var a = A2(Node,
   "a",
   _L.fromArray([b]));
```
It would be:
```javascript
   var b, a;
   b = A2(Node,
   "b",
   _L.fromArray([a]));
   a = A2(Node,
   "a",
   _L.fromArray([b]));
~~~

**Comment by zeckalpha** [comment]
My theory: when a is defined, b already exists so it works, but when b is defined, a is not declared, so it breaks.

I'll see if I can get the looping to work by manually changing the output JS.

**Comment by zeckalpha** [comment]
Nope, that didn't do it.

**Comment by zeckalpha** [comment]
Putting a closure (like recursively has you do) around it to make it lazy makes your example work.

**Comment by jdavidberger** [comment]
Yeah, it would have to have an object already in the heap that you keep around and use to work with the existing JS stuff. 

I think I'm just going to end up closuring around every node involved in a cycle. It isn't pretty; but otherwise I have to figure out/worry/rely on the ordering which I'd rather avoid, even at the expense of speed.

**Comment by zeckalpha** [comment]
Alternatively, instead of using locals and closures, would it be better to use an JS object? Putting the definitions in the export at the end might work.
~~~javascript
   {
   b: A2(Node,
   "b",
   _L.fromArray([a])),
   a: A2(Node,
   "a",
   _L.fromArray([b]))
   }
~~~

**Comment by zeckalpha** [comment]
I haven't gotten to making a corresponding issue. Did @jdavidberger or @Dandandan create one? I'm going to create one now, but either of you should close it if it's a duplicate.

**Comment by zeckalpha** [comment]
I opened elm-lang/elm-compiler#1012

**Comment by zeckalpha** [comment]
But that was a duplicate of elm-lang/elm-compiler#873
