### ISSUE TITLE
float parser broken

### ISSUE THREAD

**Issue by aforemny** [Dandandan/parser#9]
There are two issues with the `float` parser from the `Parser.Char` module.

Consider a float N.M. If N is -0, then -0.M will be parsed as 0.M, e.g.

    parseString float "-0.1" => "0.1"

If N is negative, then N.M will be parsed as N.0 + 0.M in contrast to N.0 - 0.M, e.g.

    parseString float "-1.1" => "0.9" == "-1.0" + "0.1"

The following implementation solves it for me.

    {-| Parse a float -}
    float : Parser Char Float
    float = (\s i f -> s*(toFloat i + 0.1 * foldr (\b a -> a / 10 + b) 0 (List.map toFloat f))) `Parser.map` (optional (always (-1) `Parser.map` symbol '-') 1) `and` integer <* symbol '.' `and` some digit

**Comment by Dandandan** [comment]
Thank you for mentioning this. I think I will add the optional (+) sign too.

**Comment by Dandandan** [comment]
Released in 3.1.0.
Thanks @aforemny
